customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('login/',views.accounts,name='accounts'),
     path('cart/',views.cart,name='cart')
]

hellokart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
     path('customers/', include('customers.urls')),
]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('',views.index),
]

products/urls.py
from django.urls import path
from . import views
app_name = 'products'

urlpatterns = [
    path('',views.index,name='index'),
    path('product-detail/',views.product_details,name='product_details'),
     path('all-products/',views.all_products,name='all_products'),
]

themes/urls.py
from django.urls import path
from . import views

app_name = 'themes'

urlpatterns = [
    path('',views.index),
]

customers/models.py
from django.db import models
from django.contrib.auth.models import User

# model for customers
class Customer(models.Model):
    LIVE = 1
    DELETE = 0


    DELETE_CHOICES = [
        (LIVE, 'Live'),
        (DELETE, 'Delete'),
    ]

    name= models.CharField(max_length=255)
    adress = models.TextField()  
    user= models.OneToOneField(User, on_delete=models.CASCADE,related_name= "user_profile")  
    phone = models.CharField(max_length=10)
    priority = models.IntegerField(default=0)  
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at= models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    
    def __str__(self):
                return self.name

orders/models.py
from django.db import models

from customers.models import Customer
from products.models import Product

#model for orders
class Order(models.Model):
    LIVE = 1
    DELETE = 0

    DELETE_CHOICES = [
        (LIVE, 'Live'),
        (DELETE, 'Delete'),
    ]
    CART_STAGE = 0
    ORDER_CONFIMED = 1
    ORDER_PROCESSED = 2
    ORDER_DELIVERED = 3
    ORDER_REJECTED = 4
    STATUS_CHOICES = (
        (ORDER_PROCESSED, "ORDER_PROCESSED"),
        (ORDER_DELIVERED, "ORDER_DELIVERED"),
        (ORDER_REJECTED, "ORDER_REJECTED"),
    )
    order_status = models.IntegerField(choices=STATUS_CHOICES , default= CART_STAGE)
    owner = models.ForeignKey(Customer, on_delete=models.SET_NULL, related_name="orders", null=True)
    address = models.TextField()  
    user = models.OneToOneField(Customer, on_delete=models.CASCADE, related_name="user_profile")  
    phone = models.CharField(max_length=10)
    priority = models.IntegerField(default=0)  
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return f"Order by {self.owner} at {self.created_at}"


#model for items in cart
class OrderItem(models.Model): 
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name="added_carts", null=True)
    quantity = models.IntegerField(default=1)
    owner = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="added_items")

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

products/models.py
from django.db import models


#model for products
class Product(models.Model):
    LIVE = 1
    DELETE = 0

    DELETE_CHOICES = [
        (LIVE, 'Live'),
        (DELETE, 'Delete'),
    ]

    title = models.CharField(max_length=255)
    price = models.IntegerField()  
    description = models.TextField()  
    image = models.ImageField(upload_to="products/")
    priority = models.IntegerField(default=0)  
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at= models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    
    def __str__(self):
                return self.title

themes/models.py
from django.db import models


# model for banner

class SiteSetting(models.Model):
    image = models.ImageField(upload_to="banner/")
    caption = models.TextField
    
    def __str__(self):
                return self.caption

customers/views.py
from django.shortcuts import render

app_name = 'customers'
def accounts(request):
    context={
        'title':"Red Store|Sign in or create account"

    }
    return render(request,'account.html',context=context)
def cart(request):
    context={
        'title':"Red Store|My Cart"

    }
    return render(request,'cart.html',context=context)

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render

# view for root url
app_name = 'products'
def index(request):
    context={
        'title':"Red Store|Shop swiftly"
    }
    return render(request,'index.html',context=context)
def product_details(request):
    context={
        'title':"Red Store|Product Details"

    }
    return render(request,'product_details.html',context=context)
def all_products(request):
    context={
        'title':"Red Store|All Products"

    }
    return render(request,'products.html',context=context)

themes/views.py
from django.shortcuts import render

# Create your views here.

templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include  'includes/header.html' %}
    <!-- Account Page -->
    <div class="account-page">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <img src="{% static 'images/image1.png' %}" width="100%">
                </div>
                <div class="col-2">
                    <div class="form-container">
                        <div class="form-btn">
                            <span onclick="login()">Login</span>
                            <span onclick="register()">Register</span>
                            <hr id="Indicator">
                        <form id="LoginForm">
                            <input type="text" placeholder="Username">
                            <input type="password" placeholder="Password">
                            <button type="submit" class="btn">Login</button>
                            <a href="">Forget Password</a>
                        </form>

                        <form id="RegForm">
                            <input type="text" placeholder="Username">
                            <input type="email" placeholder="Email">
                            <input type="password" placeholder="Password">
                            <button type="submit" class="btn">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


 
    {% include 'includes/footer.html' %}
    <script>
        var LoginForm = document.getElementById("LoginForm");
        var RegForm = document.getElementById("RegForm");
        var Indicator = document.getElementById("Indicator");
        function register() {
            RegForm.style.transform = "translatex(0px)";
            LoginForm.style.transform = "translatex(0px)";
            Indicator.style.transform = "translateX(100px)";

        }
        function login() {
            RegForm.style.transform = "translatex(300px)";
            LoginForm.style.transform = "translatex(300px)";
            Indicator.style.transform = "translate(0px)";

        }
    </script>
    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'js/script.js' %}" defer></script>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include  'includes/header.html' %}  <!-- Cart items details -->
    <div class="small-container cart-page">
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Subtotal</th>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="{% static 'images/buy-1.jpg' %}">
                        <div>
                            <p>Red Printed T-Shirt</p>
                            <small>Price: $50.00</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>$50.00</td>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="{% static 'images/buy-2.jpg ' %}">
                        <div>
                            <p>Red Printed T-Shirt</p>
                            <small>Price: $50.00</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>$50.00</td>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="{% static 'images/buy-3.jpg ' %}">
                        <div>
                            <p>Red Printed T-Shirt</p>
                            <small>Price: $50.00</small>
                            <br>
                            <a href="">Remove</a>
                        </div>
                    </div>
                </td>
                <td><input type="number" value="1"></td>
                <td>$50.00</td>
            </tr>
        </table>
        <div class="total-price">
            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>$200.00</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>$35.00</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>$230.00</td>
                </tr>
            </table>
        </div>
    </div>

    <!-- Footer -->
    {% include 'includes/footer.html' %}
{% endblock %}

templates/includes/footer.html
{% load static %}
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Download Our App</h3>
                <p>Download App for Android and ios mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static 'images/play-store.png' %}">
                    <img src="{% static 'images/app-store.png' %}" >
                </div>
            </div>
            <div class="footer-col-2">
                <img src="{% static 'images/logo-white.png' %}">
                <p>Our Purpose Is To Sustainably Make the Pleasure and Benefits of Sports Accessible to the Many.
                </p>
            </div>
            <div class="footer-col-3">
                <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col-4">
                <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>Instagram</li>
                    <li>Youtube</li>
                </ul>
            </div>
        </div>
        <hr>
        <p class="copyright">Copyright 2020 - Samwit Adhikary</p>
    </div>
</div>

templates/includes/header.html
{% load static %}
<div class="container">
    <div class="navbar">
        <div class="logo">
            <a href="{% url 'products:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo" width="125px"></a>
        </div>
        <nav>
            <ul id="MenuItems">
                <li><a href="{% url 'products:index' %}">Home</a></li>
                <li><a href="{% url 'products:all_products' %}">Products</a></li>
                <li><a href="{% url 'customers:accounts' %}">Account</a></li>
            </ul>
        </nav>
        <a href="{% url 'customers:cart' %}"><img src="{% static 'images/cart.png' %}" width="30px" height="30px"></a>
        <img src="{% static 'images/menu.png' %}" class="menu-icon" onclick="menutoggle()">
    </div>
</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include  'includes/header.html' %}
    
             <div class="row">
                <div class="col-2">
                    <h1>Give Your Workout <br> A New Style!</h1>
                    <p>Success isn't always about greatness. It;s about consistency. Consistent <br> hard work gains
                        success. Greatness will come.</p>
                    <a href="" class="btn">Explore Now &#8594;</a>
                </div>
                <div class="col-2">
                    <img src="{% static 'images/image1.png' %}">
                </div>
            </div>
        </div>
    </div>

    <!-- Feadtued Categories -->

    <div class="categories">
        <div class="small-container">
            <div class="row">
                <div class="col-3">
                    <img src="{% static 'images/category-1.jpg' %}">
                </div>
                <div class="col-3">
                    <img src="{% static 'images/category-2.jpg' %}">
                </div>
                <div class="col-3">
                    <img src="{% static 'images/category-3.jpg' %}">
                </div>
            </div>
        </div>
    </div>

    <!-- Featured Products -->

    <div class="small-container">
        <h2 class="title">Featured Products</h2>
        <div class="row">
            <div class="col-4">
                <a href="{% url 'products:product_details' %}"><img src="{% static 'images/product-1.jpg' %}"></a>
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-2.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-3.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-4.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
        <h2 class="title">Latest Products</h2>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/product-5.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-6.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-7.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-8.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/product-9.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-10.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-11.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-12.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
    </div>

 {% include 'includes/footer.html' %}
{% endblock %}
    

templates/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include  'includes/header.html' %}

    <!-- Single Products -->
    <div class="small-container single-product">
        <div class="row">
            <div class="col-2">
                <img src="{% static 'images/gallery-1.jpg' %}" width="100%" id="ProductImg">

                <div class="small-img-row">
                    <div class="small-img-col">
                        <img src="{% static 'images/gallery-1.jpg' %}" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="{% static 'images/gallery-2.jpg' %}" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="{% static 'images/gallery-3.jpg' %}" width="100%" class="small-img">
                    </div>
                    <div class="small-img-col">
                        <img src="{% static 'images/gallery-4.jpg' %}" width="100%" class="small-img">
                    </div>
                </div>

            </div>
            <div class="col-2">
                <p>Home / T-Shirt</p>
                <h1>Red Printed T-Shirt by HRX</h1>
                <h4>$50.00</h4>
                <select>
                    <option>Select Size</option>
                    <option>XXL</option>
                    <option>XL</option>
                    <option>L</option>
                    <option>M</option>
                    <option>S</option>
                </select>
                <input type="number" value="1">
                <a href="" class="btn">Add To Cart</a>

                <h3>Product Details <i class="fa fa-indent"></i></h3>
                <br>
                <p>Give your summer wardrobe a style upgrade with the HRX Men's Active T-Shirt. Team it with a pair of
                    shorts for your morning workout or a denims for an evening out with the guys.</p>
            </div>
        </div>
    </div>
    <!-- title -->
    <div class="small-container">
        <div class="row row-2">
            <h2>Related Products</h2>
            <p>View More</p>
        </div>
    </div>
    <!-- Products -->
    <div class="small-container">
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/product-9.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-10.jpg' %}g">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-11.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-12.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {% include 'includes/footer.html' %}
    
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include  'includes/header.html' %}

    <!-- All Products -->

    <div class="small-container">
        <div class="row row-2">
            <h2>All Products</h2>
            <select>
                <option>Default Sort</option>
                <option>Sort By Price</option>
                <option>Sort By Popularity</option>
                <option>Sort By Rating</option>
                <option>Sort By Sale</option>
            </select>
        </div>
        <div class="row">
            <div class="col-4">
                <a href="{% url 'products:product_details' %}"><img src="{% static 'images/product-1.jpg' %}"></a>
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-2.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-3.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-4.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/product-5.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-6.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-7.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-8.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/product-9.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-10.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-11.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
            <div class="col-4">
                <img src="{% static 'images/product-12.jpg' %}">
                <h4>Red Printed T-Shirt</h4>
                <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-o"></i>
                </div>
                <p>$50.00</p>
            </div>
        </div>
        <div class="page-btn">
            <span>1</span>
            <span>2</span>
            <span>3</span>
            <span>4</span>
            <span>&#8594;</span>
        </div>
    </div>

    <!-- Footer -->
    {% include 'includes/footer.html' %}

  {% endblock %}